# Setup
title:               lzhu-r
tagline:             'A place for R projects, and sometimes other stuff'
description:         'Follow along as Liang learns to make a website for his personal projects'
url:                 https://lzhu-r.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
excerpt_separator:   <!--more-->

# About/contact
author:
  name:              Liang Zhu
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
