# Setup
title:               lzhu-r
tagline:             'A place for R projects, and other stuff'
description:         'Follow Liang as he tries to figure out how to build a personal website'
url:                 https://lzhu-r.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Liang Zhu
  url:               
  email:             

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
